version: 2
updates:
  - package-ecosystem: "maven" 
    directory: "/ece-shopping"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
